# action.yml
name: 'Devesharp Action Deploy'
description: '--'
branding:
  icon: 'deploy'  
  color: 'green'
inputs:
  HOST:
    required: true
  PASSWORD:
    required: true
  PROJECT_DIR:
    required: true
  ENVIROMENTS:
    required: false
runs:
  using: 'node12'
  main: 'index.js'