# action.yml
name: 'Devesharp Action Deploy'
description: '--'
branding:
  icon: 'deploy'  
  color: 'green'
inputs:
  URL: 
    description: '--'
    required: false
runs:
  using: 'node12'
  main: 'index.js'