# action.yml
name: 'Devesharp Action Deploy'
description: '--'
branding:
  icon: 'deploy'  
  color: 'green'
inputs:
  DS_HOST:
    required: true
  DS_PASSWORD:
    required: true
  DS_USER:
    required: true
  DS_PROJECT_DIR:
    required: false
  DS_ENVIROMENTS:
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.DS_HOST }}
    - ${{ inputs.DS_PASSWORD }}
    - ${{ inputs.DS_ROOT }}
    - ${{ inputs.DS_PROJECT_DIR }}
    - ${{ inputs.DS_ENVIROMENTS }}
